#!/usr/bin/env sh

ALBUM="/tmp/mpd_mpris/artwork_*"
 
ARTIST="$(mpc -f "%artist%" | head -n 1)"

TITLE="$(mpc -f "%title%" | head -n 1)"

sleep 0.1
notify-send -i $ALBUM "$ARTIST" "$TITLE"

pkill -RTMIN+11 dwmblocks
