#!/usr/bin/env sh

ffmpeg -y -i "$HOME/music/$(mpc -f %file% current)" -an -vcodec copy /tmp/cover.jpg 2>/dev/null
 
ALBUM="/tmp/cover.jpg"

ARTIST="$(mpc -f "%artist%" | head -n 1)"

TITLE="$(mpc -f "%title%" | head -n 1)"

#sleep 0.1
dunstify -r 999 -i "$ALBUM" "$ARTIST" "$TITLE"

pkill -RTMIN+11 i3blocks
