#!/usr/bin/env sh

ffmpeg -y -i "$HOME/music/$(mpc -f %file% current)" -an -vcodec copy /tmp/cover.jpg 2>/dev/null
 
ALBUM="/tmp/cover.jpg"

ARTIST="$(mpc -f "%artist%" | head -n 1)"

TITLE="$(mpc -f "%title%" | head -n 1)"

NOTIFY_ID_FILE="/tmp/song_notify_id"

if [ -f "$NOTIFY_ID_FILE" ]; then
    NOTIFY_ID=$(cat "$NOTIFY_ID_FILE")
else
    NOTIFY_ID=0
fi

sleep 0.1
notify-send -p -i "$ALBUM" --replace-id=$NOTIFY_ID "$ARTIST" "$TITLE" > "$NOTIFY_ID_FILE"

pkill -RTMIN+11 dwmblocks
