#!/bin/sh

#Add this to your autoexec
xrdb -merge ~/.Xresources
xinput --set-prop 13 "libinput Accel Speed" -1
~/.fehbg
xrandr --output HDMI-0 --gamma 1.3:1.3:1.3
picom &
lxpolkit &
sxhkd -c ~/.config/cwm/sxhkdrc &
dunst &
~/.config/cwm/barcwm | lemonbar -n "bar" -b -f "Ttyp0:size=10" &
cwm -c ~/.config/cwm/cwmrc 
